# Generated by Django 4.0.1 on 2022-01-25 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_name', models.CharField(max_length=100)),
                ('date', models.DateField(verbose_name='race date')),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('time', models.DateTimeField(verbose_name='race time')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.schedule')),
            ],
        ),
    ]
