# Generated by Django 4.0.1 on 2022-01-26 05:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='time_p1',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='p1 time'),
        ),
        migrations.AddField(
            model_name='race',
            name='time_p2',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='p2 time'),
        ),
        migrations.AddField(
            model_name='race',
            name='time_p3',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='p3 time'),
        ),
        migrations.AddField(
            model_name='race',
            name='time_q',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='q time'),
        ),
    ]
